
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Workiva/go-datastructures"
  version = "1.0.34"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.1.2"

[[constraint]]
  branch = "elasticell"
  name = "github.com/deepfabric/etcd"

[[constraint]]
  branch = "master"
  name = "github.com/deepfabric/go-nemo"

[[constraint]]
  branch = "master"
  name = "github.com/fagongzi/goetty"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.4.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  branch = "v1"
  name = "github.com/unrolled/render"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.2.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.0.5"
