- hosts: n1 n5 n6
  remote_user: root
  tasks:
  - name: stop pd,clear pd
    shell: "{{ item }}"
    ignore_errors: yes
    with_items: 
    - kill -9 `ps -ef|grep pd.json|grep -v grep|awk '{print $2}'`
    - /opt/apps/elasticell/bin/clean.sh

- hosts: n2 n3 n4
  remote_user: root
  tasks:
  - name: stop cell,clear cell
    shell: "{{ item }}"
    ignore_errors: yes
    with_items: 
    - kill -9 `ps -ef|grep cell.json|grep -v grep|awk '{print $2}'`
    - /opt/apps/elasticell/bin/clean.sh

- hosts: n5
  remote_user: root
  tasks:
  - name: stop proxy
    shell: "{{ item }}"
    ignore_errors: yes
    with_items: 
    - kill -9 `ps -ef|grep proxy.json|grep -v grep|awk '{print $2}'`

